// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleSerach.DBContexts;

namespace VehicleSerach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200904171234_addCreate")]
    partial class addCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleSerach.Models.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body_type");

                    b.Property<string>("Chassis_Number");

                    b.Property<string>("DeviceID");

                    b.Property<string>("Engine_Number");

                    b.Property<string>("Load_carrying_capacity");

                    b.Property<string>("Make_of_vehicle");

                    b.Property<string>("Manufacturing_year");

                    b.Property<string>("Model_Number");

                    b.Property<string>("Organisation_name");

                    b.Property<string>("UserID");

                    b.Property<string>("Vehicle_Number");

                    b.Property<string>("Vehicle_Type");

                    b.HasKey("id");

                    b.ToTable("vehicles");

                    b.HasData(
                        new { id = 1, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-11 SS-1234", Vehicle_Type = "Car" },
                        new { id = 2, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-12 SS-1234", Vehicle_Type = "Car" },
                        new { id = 3, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-13 SS-1234", Vehicle_Type = "Car" },
                        new { id = 4, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-14 SS-1234", Vehicle_Type = "Car" },
                        new { id = 5, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-15 SS-1234", Vehicle_Type = "Car" },
                        new { id = 6, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-16 SS-1234", Vehicle_Type = "Car" },
                        new { id = 7, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-17 SS-1234", Vehicle_Type = "Car" },
                        new { id = 8, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-18 SS-1234", Vehicle_Type = "Car" },
                        new { id = 9, Body_type = "New", Chassis_Number = "13245", DeviceID = "345", Engine_Number = "1234", Load_carrying_capacity = "500000", Make_of_vehicle = "India", Manufacturing_year = "2001", Model_Number = "345", Organisation_name = "India", UserID = "1", Vehicle_Number = "MH-19 SS-1234", Vehicle_Type = "Car" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
